title: "CondorHalcon"
titlecaps: "CONDORHALCON"
inMaintenance: true
contact:
    name: "CondorHalcon"
    email2: "condorhalcon20@gmail.com"
    discord:
        text: "discord.gg/x7qNK3e447"
        url: "https://discord.gg/x7qNK3e447"
    github:
        tag: "@CondorHalcon"
        url: "https://github.com/CondorHalcon"
description: >
    This site is a Portfolio for CondorHalcon.
webhost:
    name: "Github Pages"
    url: "https://pages.github.com/"

defaults:
    -
        scope:
            path: "docs"
            type: "pages"
        values:
            layout: "default"
            title: "Page"
            maintenancePage: false
    -
        scope:
            path: "docs/projectPages"
            type: "pages"
        values:
            layout: "product"
            title: "Product"
            maintenancePage: false

            product:
                cover: /assets/png/default_cover_pic.png
                developer: "Developer"
                publisher: "Publisher"
                short: "This is a short product description"
                involement: "This describes my part and work in the project."
                screenshots: [/assets/png/default_screenshot_pic.png]

            stores:
                web:
                    bool: false
                    text: "Website"
                    icon: ""
                    url: "condorhalcon.github.io"
                github:
                    bool: false
                    text: "GitHub"
                    icon: ""
                    url: "https://github.com"
                steam:
                    bool: false
                    text: "Steam"
                    icon: ""
                    url: "https://store.steampowered.com"
                epicgames:
                    bool: false
                    text: "Epic Games"
                    icon: ""
                    url: "https://www.epicgames.com/"
                itch:
                    bool: false
                    text: "itch.io"
                    icon: ""
                    url: "https://itch.io/"

# For running jekyll localy
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
