# Config
title: "CondorHalcon"
titlecaps: "CONDORHALCON"
name: "Judah Hawi"
email: judah.hawi@condorhalcon.com
description: >- # this means to ignore newlines until "baseurl:"
  Judah Hawi, game developer and programmer, specializing in Unity and Unreal Engine. Explore my portfolio showcasing game development projects, programming expertise, and creative solutions. Contact me for collaboration or inquiries.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.condorhalcon.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  CondorHalcon
webhost:
    name: "Github Pages"
    url: "https://pages.github.com/"
featuredIndex: 0

# Build settings
theme: condor-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
inMaintenance: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - theme/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Data
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            class: all
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
            class: page
    -
        scope:
            path: "_posts/"
            type: "posts"
        values:
            layout: "post"
            title: "Project"
            class: post

            project:
                cover: /assets/png/placeholder_cover.png
                developer: "~Developer"
                publisher: "~Publisher"
                screenshots: [/assets/png/placeholder_FHD.png]

            stores:
                -
                    tags: "website"
                    text: "Website"
                    icon: ""
                    url: "https://condorhalcon.com"
                -
                    tags: "github"
                    text: "GitHub"
                    icon: ""
                    url: "https://github.com"
                -
                    tags: "steam"
                    text: "Steam"
                    icon: ""
                    url: "https://store.steampowered.com"
                -
                    tags: "epicgames"
                    text: "Epic Games"
                    icon: ""
                    url: "https://www.epicgames.com/"
                -
                    tags: "itch"
                    text: "itch.io"
                    icon: ""
                    url: "https://itch.io/"
