title: "CondorHalcon"
titlecaps: "CONDORHALCON"
contact:
  name: "CondorHalcon"
  email2: "judahhohawi@outlook.com"
  discord:
    text: "discord.gg/x7qNK3e447"
    url: "https://discord.gg/x7qNK3e447"
host:
  name: "Github Pages"
  url: "https://pages.github.com/"
  