title: "CondorHalcon"
titlecaps: "CONDORHALCON"
inMaintenance: true
contact:
    name: "CondorHalcon"
    email2: "judahhohawi@outlook.com"
    discord:
        text: "discord.gg/x7qNK3e447"
        url: "https://discord.gg/x7qNK3e447"
    description: >
        My name is CondorHalcon, I am a game developer.
host:
    name: "Github Pages"
    url: "https://pages.github.com/"

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
            title: "Page"
            maintenancePage: false
  