title: "CondorHalcon"
titlecaps: "Judah Hawi | CONDORHALCON"
inMaintenance: false
contact:
    name: "CondorHalcon"
    email: "condorhalcon20@gmail.com"
    discord:
        text: "discord.gg/x7qNK3e447"
        url: "https://discord.gg/x7qNK3e447"
    github:
        tag: "@CondorHalcon"
        url: "https://github.com/CondorHalcon"
webhost:
    name: "Github Pages"
    url: "https://pages.github.com/"

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            class: all
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
            class: page
    -
        scope:
            path: "_posts/"
            type: "posts"
        values:
            layout: "post"
            title: "Project"
            class: post

            project:
                cover: /assets/png/placeholder_cover.png
                developer: "~Developer"
                publisher: "~Publisher"
                screenshots: [/assets/png/placeholder_FHD.png]

            stores:
                web:
                    bool: false
                    text: "Website"
                    icon: ""
                    url: "https://condorhalcon.com"
                github:
                    bool: false
                    text: "GitHub"
                    icon: ""
                    url: "https://github.com"
                steam:
                    bool: false
                    text: "Steam"
                    icon: ""
                    url: "https://store.steampowered.com"
                epicgames:
                    bool: false
                    text: "Epic Games"
                    icon: ""
                    url: "https://www.epicgames.com/"
                itch:
                    bool: false
                    text: "itch.io"
                    icon: ""
                    url: "https://itch.io/"
